# Generated by Django 3.0.7 on 2020-06-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxes',
            options={'ordering': ['datetime']},
        ),
        migrations.RenameField(
            model_name='boxes',
            old_name='dateTime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='boxes',
            old_name='projectName',
            new_name='projectname',
        ),
    ]
